### PR TITLE
Fix DwCA exporting

### LINKED ISSUE #7856: DwCA exporting fails
**Describe the bug**
Exporting to DwCA is failing on `v7.12.0-prerelease`

**To Reproduce**

1. Log in as `collection` in a [copy of this database](https://drive.google.com/file/d/1hZZruSqI0wNs2fGiH1dpFNRA5yze527F/view?usp=sharing)
2. Go to **User Tools**
3. Click on **Update RSS Feed**
4. See that it succeeds, you should be notified with ZIP archives to download

This works on `v7.11.4`, but fails on `v7.12.0-prerelease`. This fails when updating the RSS feed _and_ when creating an export manually (by selecting the mapping and metadata).

### 7.11.4

Image

### 7.12.0-prerelease

```
AttributeError: Neither 'Case' object nor 'Comparator' object has an attribute 'class_'\n"}
```

Full trace:

```
"traceback":"Traceback (most recent call last):\n  File \"/opt/specify7/ve/lib/python3.12/site-packages/sqlalchemy/sql/elements.py\", line 858, in __getattr__\n    return getattr(self.comparator, key)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Comparator' object has no attribute 'class_'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/specify7/specifyweb/backend/export/views.py\", line 169, in try_update_feed\n    update_feed(force=True, notify_user=user)\n  File \"/opt/specify7/specifyweb/backend/export/feed.py\", line 58, in update_feed\n    make_dwca(collection, user, dwca_def, temp_file, eml=eml)\n  File \"/opt/specify7/specifyweb/backend/export/dwca.py\", line 215, in make_dwca\n    query_to_csv(session, collection, user, query.tableid, query.get_field_specs(), path,\n  File \"/opt/specify7/specifyweb/backend/stored_queries/execution.py\", line 309, in query_to_csv\n    query, __ = build_query(\n                ^^^^^^^^^^^^\n  File \"/opt/specify7/specifyweb/backend/stored_queries/execution.py\", line 987, in build_query\n    formatted_field = query.objectformatter.fieldformat(fs, field)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/specify7/specifyweb/backend/stored_queries/format.py\", line 402, in fieldformat\n    field = self._fieldformat(field_spec.table, field_spec.get_field(), field)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/specify7/specifyweb/backend/stored_queries/format.py\", line 436, in _fieldformat\n    return self._dateformat(specify_field, field)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/specify7/specifyweb/backend/stored_queries/format.py\", line 409, in _dateformat\n    prec_fld = getattr(field.class_, specify_field.name + 'Precision', None)\n                       ^^^^^^^^^^^^\n  File \"/opt/specify7/ve/lib/python3.12/site-packages/sqlalchemy/sql/elements.py\", line 860, in __getattr__\n    util.raise_(\n  File \"/opt/specify7/ve/lib/python3.12/site-packages/sqlalchemy/util/compat.py\", line 211, in raise_\n    raise exception\nAttributeError: Neither 'Case' object nor 'Comparator' object has an attribute 'class_'\n"}
```

### PR DESCRIPTION
**Pull request by alesan99**
Fixes #7856

Adds an extra check to field formatters to prevent crashing. I haven't found the root cause of the regression, however.

### Checklist

- [ ] Self-review the PR after opening it to make sure the changes look good and
      self-explanatory (or properly documented)
- [ ] Add relevant issue to release milestone
- [ ] Add pr to documentation list
- [ ] Add automated tests

### Testing instructions
- Open User Tools
- Click 'Create DwC Archive' and create an archive
- [ ] There is no error when creating a DwC archive on your database.
- Log into the database from the original issue https://github.com/specify/specify7/issues/7856
- [ ] There is no error when creating a DwC archive in the database from the issue.

### CODE REVIEW

**Review by CarolineDenis — APPROVED** [review]

**Review by emenslin — APPROVED** [review]
- [x] There is no error when creating a DwC archive on your database.
- [x] There is no error when creating a DwC archive in the database from the issue.

Looks good, DwcA is exported without error!

**Review by bhumikaguptaa — APPROVED** [review]
- [X] There is no error when creating a DwC archive on your database.
- [X] There is no error when creating a DwC archive in the database from the issue.

--
Works as expected, I didn't come across any error.

**Review by Iwantexpresso — CHANGES_REQUESTED** [review]
- [ ]  There is no error when creating a DwC archive on your database.
HI whenever I run the example DwCA found in:
https://discourse.specifysoftware.org/t/exporting-publishing-data-using-darwin-core-dwc-a-gbif-idigbio-etc/568

I get the following error: 
[3ckH2Lef.txt](https://github.com/user-attachments/files/26354105/3ckH2Lef.txt)

This was tested on CalvertMarine museum Db and I'm currently attempting to test this on the saiab database

**Review by grantfitzsimmons — APPROVED** [review]
- [X] There is no error when creating a DwC archive on your database.
- Log into the database from the original issue https://github.com/specify/specify7/issues/7856
- [X] There is no error when creating a DwC archive in the database from the issue.

These testing instructions do not seem very robust, but I've verified on 3 databases, including the original, that exporting is working 😄
